version: "2"
services:
  nginx:
    restart: always
    build: ./nginx
    links:
      - node1:node1
    ports:
      - "80:80"
  node1:
    build: .
    volumes:
      - ./:/app
    links:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db